interesting_things = [
    "Hiking",
    "Reading",
    "Traveling",
    "Cooking",
    "Photography",
    "Gardening",
    "Cycling",
    "Painting",
    "Writing",
    "Music",
    "Dancing",
    "Yoga",
    "Meditation",
    "Fishing",
    "Bird Watching",
    "Astronomy",
    "Collecting (stamps, coins, etc.)",
    "Knitting/Crocheting",
    "Woodworking",
    "Volunteering",
    "Learning New Languages",
    "Gaming",
    "DIY Projects",
    "Camping",
    "Surfing",
    "Skiing/Snowboarding",
    "Rock Climbing",
    "Scuba Diving",
    "Martial Arts",
    "Theater/Acting",
    "Genealogy",
    "Travel Blogging",
    "Podcasting",
    "Home Brewing",
    "Wine Tasting",
    "Car Restoration",
    "Model Building",
    "Magic Tricks",
    "Puzzle Solving",
    "Chess",
    "Board Games",
    "Cooking/Baking",
    "Fitness Training",
    "Running",
    "Swimming",
    "Archery",
    "Horseback Riding",
    "Sailing",
    "Kite Flying",
    "Calligraphy",
    "Pottery",
    "Jewelry Making",
    "Scrapbooking",
    "Origami",
    "Traveling",
    "Volunteering",
    "Learning New Languages",
    "Gaming",
    "DIY Projects",
    "Camping",
    "Surfing",
    "Skiing/Snowboarding",
    "Rock Climbing",
    "Scuba Diving",
    "Martial Arts",
    "Theater/Acting",
    "Genealogy",
    "Travel Blogging",
    "Podcasting",
    "Home Brewing",
]
